apiVersion: apps/v1
kind: Deployment
metadata:
  name: briareus-deployment
  labels:
    type: restapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: briareus
  template:
    metadata:
      labels:
        app: briareus
    spec:
      containers:
      - name: briareus
        image: jaygokani/briareus:v2
        ports:
        - containerPort: 5000