apiVersion: apps/v1
kind: Deployment
metadata:
  # name: {{ .Values.name }}-deployment
  name: {{ .Values.name }}
  # labels:
  #   type: {{ .Values.deploymentType }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        # image: jaygokani/briareus:v2
        image: docker.io/jaygokani/briareus:v2
        ports:
        - containerPort: 5000
        command: ["python3", "app.py"]