apiVersion: v1
kind: Service
metadata:
  # name: {{ .Values.name }}-service
  name: {{ .Values.name }}
spec:
  # type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  # type: NodePort
  type: LoadBalancer